services:
  wuzapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7926:7926"
    environment:
      - WUZAPI_ADMIN_TOKEN=H4Zbhw72PBKdTIgS
      - DB_USER=postgres
      - DB_PASSWORD=evpR2Xkm6B4nkrmYQBStQ61MTtZvbe4vulWJQYflJwnPBCzoPiID66tsryBDrXuZ
      - DB_NAME=postgres
      - DB_HOST=lc4co8wo8kow8swock0skk4c
      - DB_PORT=5432
      - TZ=Asia/Jakarta
      - WEBHOOK_FORMAT=json
      - SESSION_DEVICE_NAME=WuzAPI
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wuzapi-network
    restart: on-failure

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: evpR2Xkm6B4nkrmYQBStQ61MTtZvbe4vulWJQYflJwnPBCzoPiID66tsryBDrXuZ
      POSTGRES_DB: postgres
    ports:
      - "6454:6454"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wuzapi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wuzapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
      
networks:
  wuzapi-network:
    driver: bridge

volumes:
  db_data:
