version: '3.8'

services:
  wuzapi:
    build:
      context: https://github.com/PegeDev/wuzapi.git#main
      dockerfile: Dockerfile
    container_name: wuzapi
    restart: unless-stopped
    ports:
      - "8080:8080"  # Menggunakan port 8080 sesuai log
    environment:
      # Konfigurasi Database
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-wuzapi_user}
      - DB_PASSWORD=${DB_PASSWORD:-GantiDenganPasswordDB}
      - DB_NAME=${DB_NAME:-wuzapi_db}
      
      # Konfigurasi Aplikasi
      - PORT=8080
      - WUZAPI_ADMIN_TOKEN=${ADMIN_TOKEN:-GantiDenganTokenAman}
      - TZ=Asia/Jakarta
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_FORMAT=json
      - SESSION_DEVICE_NAME=WuzAPI-Coolify
      - DISABLE_RABBITMQ=true  # Nonaktifkan RabbitMQ
      
    command: sh -c "touch /.env && npm start"  # Solusi file .env
      
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wuzapi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    container_name: wuzapi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-wuzapi_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-GantiDenganPasswordDB}
      POSTGRES_DB: ${DB_NAME:-wuzapi_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wuzapi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-wuzapi_user}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  wuzapi-network:
    driver: bridge

volumes:
  postgres_data:
